// AUTO-GENERATED by train_digit_model_vscode.py -- do not hand-edit.
// Source: digit_model_int8.tflite  (12312 bytes)
#ifndef DIGIT_MODEL_DATA_H_
#define DIGIT_MODEL_DATA_H_

extern const unsigned char g_digit_model_data[];
extern const int g_digit_model_data_len;

#endif  // DIGIT_MODEL_DATA_H_
