// AUTO-GENERATED by model_to_c_array.py -- do not hand-edit.
// Class order matches the model's training/output index order exactly.
// 11 classes total: digits 0-9 and the decimal point. There is
// intentionally NO minus/dash class -- the target LCD panel never
// displays negative readings.
#ifndef DIGIT_LABELS_H_
#define DIGIT_LABELS_H_

#define DIGIT_NUM_CLASSES 11

static const char kDigitClassChars[DIGIT_NUM_CLASSES] = { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '.' };

static inline char digitClassToChar(int cls) {
  if (cls < 0 || cls >= DIGIT_NUM_CLASSES) return '?';
  return kDigitClassChars[cls];
}

#endif  // DIGIT_LABELS_H_
